apiVersion: apps/v1
kind: Deployment
metadata:
  name: jsoncrack-deployment
  labels:
    app: jsooncrack
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jsoncrack
  template:
    metadata:
      labels:
        app: jsoncrack
    spec:
      containers:
      - name: jsoncrack
        image: jsoncrack:latest
        ports:
        - containerPort: 80
